version: '3.8'

services:
  vault:
    image: bydan/vault:1.13.2
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-server.hcl
    cap_add:
      - IPC_LOCK
